server:
  port: 1111
  servlet:
    context-path: /
spring:
  profiles:
    active: dev
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
    mongodb:
      uri: mongodb://localhost:27017/mongodb
  thymeleaf:
    cache: false
  aop:
    proxy-target-class: true
  cache:
    type: redis
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    publisher-confirm: true # 如果对异步消息需要回调必须设置为true
mybatis:
  type-aliases-package: com.tengda.dazahui.system.domian
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



